#!/bin/bash
# pr_report.sh
# Posts a condensed security report to PRs (sonar + npm audit + snyk)

set -e

# Skip if not in PR context
if [ -z "$BITBUCKET_PR_ID" ]; then
  echo "Not in PR context - skipping PR report"
  exit 0
fi

# Source shared utilities
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/report_utils.sh"

echo "=== Generating PR Security Report ==="

# Get project key
PROJECT_KEY=$(get_project_key)

#######################################
# RUN SCANS
#######################################
run_npm_audit
echo "npm audit - Critical: ${NPM_CRITICAL}, High: ${NPM_HIGH}, Moderate: ${NPM_MODERATE}, Low: ${NPM_LOW}"

run_snyk_scan
if [ -n "$SNYK_TOKEN" ]; then
  echo "Snyk - Critical: ${SNYK_CRITICAL}, High: ${SNYK_HIGH}, Medium: ${SNYK_MEDIUM}, Low: ${SNYK_LOW}"
else
  echo "SNYK_TOKEN not set - skipping Snyk scan"
fi

fetch_sonarqube "$PROJECT_KEY"
echo "SonarQube - QG: ${SONAR_QG_STATUS}, Bugs: ${SONAR_BUGS}, Vulns: ${SONAR_VULNS}"

#######################################
# BUILD REPORT
#######################################
echo ""
echo "Building PR report..."

# Determine status icons
SONAR_ICON=$(get_status_icon "sonar" "${SONAR_BUGS:-0}" "${SONAR_VULNS:-0}")
NPM_ICON=$(get_status_icon "npm" "$NPM_CRITICAL" "$NPM_HIGH" "$NPM_MODERATE")

if [ -z "$SNYK_TOKEN" ]; then
  SNYK_ICON=":grey_question:"
else
  SNYK_ICON=$(get_status_icon "snyk" "$SNYK_CRITICAL" "$SNYK_HIGH" "$SNYK_MEDIUM")
fi

# Build compact report
SONAR_TOTAL=$((${SONAR_BUGS:-0} + ${SONAR_VULNS:-0} + ${SONAR_SMELLS:-0}))
REPORT="## :shield: Security Report\n\n"
REPORT+="| Check | Status | Details |\n"
REPORT+="|-------|--------|----------|\n"
REPORT+="| SonarQube | ${SONAR_ICON} ${SONAR_QG_STATUS} | ${SONAR_BUGS:-0} bugs, ${SONAR_VULNS:-0} vulns, ${SONAR_SMELLS:-0} smells |\n"
REPORT+="| npm audit | ${NPM_ICON} ${NPM_TOTAL} issues | C:${NPM_CRITICAL} H:${NPM_HIGH} M:${NPM_MODERATE} L:${NPM_LOW} |\n"

if [ -z "$SNYK_TOKEN" ]; then
  REPORT+="| Snyk | ${SNYK_ICON} Skipped | SNYK_TOKEN not configured |\n"
else
  SNYK_TOTAL=$((SNYK_CRITICAL + SNYK_HIGH + SNYK_MEDIUM + SNYK_LOW))
  REPORT+="| Snyk | ${SNYK_ICON} ${SNYK_TOTAL} issues | C:${SNYK_CRITICAL} H:${SNYK_HIGH} M:${SNYK_MEDIUM} L:${SNYK_LOW} |\n"
fi

if [ -n "$SONAR_HOST_URL" ]; then
  REPORT+="\n[View SonarQube Dashboard](${SONAR_HOST_URL}/dashboard?id=${PROJECT_KEY})\n"
fi

REPORT+="\n_Generated by CI/CD Pipeline | $(get_timestamp)_\n"

REPORT=$(echo -e "$REPORT")

# Print to console
echo ""
echo "=== PR Security Report ==="
echo -e "$REPORT"

#######################################
# POST TO BITBUCKET PR
#######################################
post_to_pr "$REPORT"

echo ""
echo "=== PR Report Complete ==="
