definitions:
  steps:
    - step: &run-tests
        name: Run Playwright Tests
        runs-on:
          - self.hosted
          - linux.shell
          - qa.test.22
        script:
          - chmod +x ./scripts/run-tests.sh
          - ./scripts/run-tests.sh "$TEST_ENV" "$TEST_GROUP"
        after-script:
          - rm -f ./.env-cmdrc.json
        artifacts:
          - playwright-report/**
          - test-results/**

pipelines:
  branches:
    develop:
      - step:
          <<: *run-tests
          name: Smoke Tests (develop)
          script:
            - chmod +x ./scripts/run-tests.sh
            - ./scripts/run-tests.sh test smoke

    test:
      - step:
          <<: *run-tests
          name: Smoke Tests (test)
          script:
            - chmod +x ./scripts/run-tests.sh
            - ./scripts/run-tests.sh test smoke

    qa:
      - step:
          <<: *run-tests
          name: Regression Tests (qa)
          script:
            - chmod +x ./scripts/run-tests.sh
            - ./scripts/run-tests.sh qa regression

  custom:
    run-tests:
      - variables:
          - name: TEST_ENV
            default: 'test'
            allowed-values:
              - 'test'
              - 'qa'
              - 'prod'
          - name: TEST_GROUP
            default: 'smoke'
            allowed-values:
              - 'smoke'
              - 'regression'
      - step: *run-tests
